FROM node:18-alpine AS builder

RUN npm install -g pnpm

WORKDIR /app
COPY pnpm-lock.yaml ./
RUN pnpm fetch

COPY . ./
RUN pnpm install --offline --frozen-lockfile
RUN pnpm build

EXPOSE 3000
CMD [ "pnpm", "start" ]